### ISSUE TITLE
Wrong version on the "Installed plugins" page

### ISSUE THREAD

**Issue by mashabow** [gitbucket/gitbucket-gist-plugin#24]
I installed `gitbucket-gist-plugin_2.11-3.11.0.jar` on GitBucket 3.11, but it is displayed as version 3.6 on the "Installed plugins" page.

![plugins](https://cloud.githubusercontent.com/assets/6268183/13274905/93ea2ad4-daf2-11e5-8546-b72e00715c98.png)

**Comment by McFoggy** [comment]
The version of the plugin is not the same as the version of the container.
It is up to the plugins maintainer to update their declared version when they release a new plugin version. In current gitbucket implementation, version shown on plugin screen is the latest declared by the Plugin class of the loaded plugin.
For the gist plugin this version has not been touched since 3.6
![image](https://cloud.githubusercontent.com/assets/1119660/13278154/71829c84-dace-11e5-8550-200cdb9bb7cc.png)

**Comment by mashabow** [comment]
Ah, so it is not a bug?

**Comment by McFoggy** [comment]
I have not said that.

**Comment by takezoe** [comment]
@mashabow Sorry for my slow reply. This is my mistake. Currently, gist-plugin is 4.0.0 but displayed as 2.0.0 at the installed plugin list. I will fix version at installed the plugin list in the next release of gist-plugin.
